### ISSUE TITLE
New Feature: Hide Thumbnails

### ISSUE THREAD

**Issue by Pedro-Gregorio** [Pedro-Gregorio/TubeMod#17]
This feature aims to hide every thumbnail across YouTube.
Should probably be considered a general feature instead of only on the home page, subscriptions, or video recommendations.

**Comment by Myouboku** [comment]
I tried something with this XPath : `//ytd-thumbnail | //ytd-playlist-thumbnail | //div[@id='video-preview']`

What it does :
- Hide videos thumbnails
- Hide playlists thumbnails
- Hide videos preview bar on hover

What it doesn't :
- Hide shorts thumbnails

I didn't opened a PR as the way the extension works at this time makes that feature really CPU intensive and the final rendering isn't great at all... Here's [a video](https://youtu.be/zTVJVDLaQFs) to show what's wrong. You can't hear it but my PC is burning --'

**Comment by Perseus333** [comment]
Maybe try adding this: `//ytm-shorts-lockup-view-model/a` so that it looks like:

```
//ytd-thumbnail | //ytd-playlist-thumbnail | //div[@id='video-preview'] | //ytm-shorts-lockup-view-model/a
```
This should hide shorts thumbnails.
Regarding the CPU usage, I don't know what is causing it besides maybe that some of the paths are too general? Maybe it has something to do with `//div[@id='video-preview']` that maybe makes it check all divs? I'm not sure.

**Comment by Myouboku** [comment]
It effectively did the trick for thumbnails, thanks !

I tried basing it on the id attributs first and it was the same, that's why I ended up with tags as I preferred the readability. But I may have written a bad XPath syntax, I'll give it another try later and see if I can get more details on what's causing bad performance

**Comment by Perseus333** [comment]
Update:

- `//ytd-search-refinement-card-renderer/a/div[@id='card-thumbnail']` Removes the thumbnails in search suggestions
- `//div[@id='thumbnail']` Removes the thumbnails in the chapters of the videos

```
//ytd-thumbnail | //ytd-playlist-thumbnail | //div[@id='video-preview'] | //ytm-shorts-lockup-view-model/a | ytd-search-refinement-card-renderer | //ytd-search-refinement-card-renderer/a/div[@id='card-thumbnail'] | //div[@id='thumbnail']
```

**Comment by Perseus333** [comment]
The memory usage issue might be a local one, because in my machine chromium reports that the extension is using "just" 20-40 MB of RAM when spamming toggle on and off thumbnails or loading new ones repeatedly.

**Comment by Pedro-Gregorio** [comment]
Releasing on 1.6.0, closing the issue for the time being.
