### ISSUE TITLE
Hide "Watch Later" incorrectly works

### ISSUE THREAD

**Issue by paragraphhh** [Pedro-Gregorio/TubeMod#40]
For users who have the 'Your Movies & TV' tab in the sidebar, that feature is hidden instead, resulting in all of the following tabs to be offset, and hide the previous tab when the features are enabled.
This feature is presumably region-based.

![image](https://github.com/user-attachments/assets/ebf5a12a-451c-4c04-a2fd-80c912f2e2f9)

**Comment by Perseus333** [comment]
Hi, the incorrect behavior should be fixed once [d527c3e](https://github.com/Pedro-Gregorio/TubeMod/pull/34/commits/d527c3eb3fdb6d94340a4f6954c1e7ced35af4e9) is merged This is because the old version relies on index numbers instead of identifying elements of the sidebar buttons.

However, to remove "Your movies & TV" I would need to know the href of the element to implement it myself, or anyone that also has this section in their sidebar to fix it.

If you could go in your browser, open youtube and in the console paste `$x("//ytd-guide-entry-renderer")` and then locate from the elements that it will give you the one that is associated with "Your movies & TV". Then, once you are in the html tab of the inspect tool, go to it's first children that it should be an `<a>` and just give the value of the href in that element. With that we can identify the element and be able to add a toggle for it.

**Comment by Rashnain** [comment]
I have it, the href is `/feed/storefront?bp=ogUCKAQ%3D`

**Comment by Perseus333** [comment]
With [ef1a76c](https://github.com/Pedro-Gregorio/TubeMod/pull/34/commits/ef1a76cc213143ea2b92471b5e209c9f50cd2701) once it gets merged this issue should now be resolved.

**Comment by Pedro-Gregorio** [comment]
@Perseus333 and @Rashnain thank you for your help! 
@paragraphhh should be fixed in 1.5.0!
