### ISSUE TITLE
"TubeMod wants access to this site"

### ISSUE THREAD

**Issue by tarsnip** [Pedro-Gregorio/TubeMod#66]
TubeMod is requesting access to every website
![Screenshot from 2024-10-05 13-06-29](https://github.com/user-attachments/assets/523e9b62-ccac-46e1-8027-2c38fd669561)

**Comment by Pedro-Gregorio** [comment]
Hey there! That is wierd, and doesn't look alright. TubeMod only needs to access to Youtube:
![image](https://github.com/user-attachments/assets/f1718852-5d0e-4797-b62f-87b20fbbbb94)

I would say the reason you're getting that alert is because you do have YouTube open in a tab. If you try to use the extension outside of YouTube, it will validate that you're not in YouTube and, therefore, will get that message.
